---
pipeline: 2019_07_11_JUMP-CP
output_dir: profiles
platemap_well_column: Metadata_well_position
compartments:
  - cells
  - cytoplasm
  - nuclei
aggregate:
  perform: false
  plate_column: Metadata_Plate
  well_column: Metadata_Well
  method: median
  fields: all
  image_feature_categories:
    - Count
    - Intensity
annotate:
  perform: true
  well_column: Metadata_Well
  external:
    perform: true
    file: JUMP-Target-1_compound_metadata.tsv
    merge_column: broad_sample
normalize:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: false
normalize_negcon:
  perform: true
  method: mad_robustize
  features: infer
  mad_robustize_fudge_factor: 0
  image_features: false
feature_select:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: false
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
feature_select_negcon:
  perform: true
  features: infer
  level: batch
  gct: false
  image_features: false
  operations:
    - variance_threshold
    - correlation_threshold
    - drop_na_columns
    - blocklist
quality_control:
  perform: true
  summary:
    perform: true
    row: Metadata_Row
    column: Metadata_Col
  heatmap:
    perform : true
options:
  compression: gzip
  float_format: "%.5g"
  samples: all
---
batch: 2020_12_08_CPJUMP1_Bleaching
plates:
  - name: BR00116991A
    process: true
  - name: BR00116991B
    process: true
  - name: BR00116991C
    process: true
  - name: BR00116991D
    process: true
  - name: BR00116991E
    process: true
  - name: BR00116991F
    process: true
  - name: BR00116992A
    process: true
  - name: BR00116992B
    process: true
  - name: BR00116992C
    process: true
  - name: BR00116992D
    process: true
  - name: BR00116992E
    process: true
  - name: BR00116992F
    process: true
  - name: BR00116993A
    process: true
  - name: BR00116993B
    process: true
  - name: BR00116993C
    process: true
  - name: BR00116993D
    process: true
  - name: BR00116993E
    process: true
  - name: BR00116993F
    process: true
  - name: BR00116994A
    process: true
  - name: BR00116994B
    process: true
  - name: BR00116994C
    process: true
  - name: BR00116994D
    process: true
  - name: BR00116994E
    process: true
  - name: BR00116994F
    process: true
process: true